name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Setup bats
      uses: mig4/setup-bats@v1
      with:
        bats-version: 1.2.1

    - name: Setup kcov
      run: |-
        sudo apt install libcurl4-openssl-dev libelf-dev libdw-dev cmake &&
        wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
        tar xzf master.tar.gz &&
        cd kcov-master &&
        mkdir build &&
        cd build &&
        cmake .. &&
        make &&
        sudo make install &&
        cd ../.. &&
        rm -rf kcov-master

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Test with coverage
      run: |-
        mkdir -p coverage &&
        kcov coverage bats test &&
        bash <(curl -s https://codecov.io/bash)
